CREATE TABLE wallets (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(128) NOT NULL UNIQUE CHECK (name <> ''),
    account numeric NOT NULL DEFAULT '0.00' CHECK (account >= '0.00')
);
