CREATE TABLE transactions(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    operation integer NOT NULL CHECK(operation >= 1),
    wallet_id bigint NOT NULL REFERENCES wallets(id),
    amount numeric NOT NULL CHECK(amount > '0.00')
);
