version: "3.7"

services:
  postgres:
    restart: always
    image: postgres:10
    env_file:
      - .env
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data:


