basePath: /api/v1
info:
  contact:
    email: potalestor@gmail.com
    name: '@potalestor'
  description: Swagger API for Golang Project CUSTOM-WALLET.
  title: CUSTOM-WALLET REST API
  version: 0.0.1
paths: {}
swagger: "2.0"
